USE [master]
GO

/****** Object:  Database [ProgePodKartTest]    Script Date: 13.02.2022 05:17:01 ******/
CREATE DATABASE [ProgePodKartTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProgePodKartTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ProgePodKartTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProgePodKartTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ProgePodKartTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProgePodKartTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProgePodKartTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProgePodKartTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProgePodKartTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProgePodKartTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProgePodKartTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProgePodKartTest] SET  MULTI_USER 
GO

ALTER DATABASE [ProgePodKartTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProgePodKartTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProgePodKartTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProgePodKartTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProgePodKartTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProgePodKartTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProgePodKartTest] SET  READ_WRITE 
GO


